project: 
  type: website
  execute-dir: project

execute: 
  freeze: true
  engine: knitr

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
    R.options:
      width: 120

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-link: true
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px