project: 
  type: website
  execute-dir: project
  

execute: 
  freeze: auto
  engine: knitr
  port: 8877
  cache: true

knitr:
  opts_chunk:
    R.options:
      width: 120

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-tools: true
    code-fold: true
    code-overflow: wrap
    page-layout: full
    css: styles.css

website:
  title: "Free time & chunking modeling"
  description: "A project about..."
  back-to-top-navigation: true
  page-navigation: true
  repo-url: "https://github.com/venpopov/ltmTimeBenefit"
  search: true
  navbar: 
    left: 
      - text: "Versions"
        menu:
          - text: "Latest"
            href: "https://venpopov.github.io/ltmTimeBenefit/index.html"
          - text: "v0.1"
            href: "https://venpopov.github.io/ltmTimeBenefit/v0.1/index.html"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: "https://github.com/venpopov/ltmTimeBenefit"
          - text: Report a Bug
            href: "https://github.com/venpopov/ltmTimeBenefit/issues"
  sidebar: 
   collapse-level: 1
   contents: 
     - section: "<i>Version {{< env DOCS_VERSION >}}</i>"
     - section: "&nbsp;"
     - index.qmd
     - section: "Development notes"
       contents: 
       - "docs/notes.qmd"
       - auto: "docs/dev-notebooks/*"
     - section: "Notebooks"
       contents: 
         - section: "Data"
           contents:
             - "docs/notebooks/data_structure.qmd"
             - "docs/notebooks/EDA.qmd"
             - "docs/notebooks/subject_data.qmd"
         - section: "Model 1: Original model"
           contents:
            - "docs/notebooks/modelling_edas_approach.qmd"
            - "docs/notebooks/par_identifiability.qmd"
            - "docs/notebooks/sensitivity-to-tau.qmd"
            - "docs/notebooks/exp3_model1.qmd"
            - "docs/notebooks/model-explore.qmd"
         - section: "Model 2: Include encoding time"
           contents:
            - "docs/notebooks/model_v2.qmd"
         
         - section: "Model 3: Non-linear recovery"
           contents:
            - "docs/notebooks/non_linear_recovery.qmd"
            - "docs/notebooks/model3_basic_fits.qmd"
            - "docs/notebooks/model3_bootstrap.qmd"
            - "docs/dev-notebooks/new_model_eq.qmd"
            - "docs/notebooks/linear-recovery-random-variable.qmd"
     - section: "Function reference"
       contents: docs/reference/*
  draft-mode: unlinked

editor:
  render-on-save: true
