project: 
  type: website
  execute-dir: project
  

execute: 
  freeze: true
  engine: knitr
  port: 8877

freeze: true

knitr:
  opts_chunk:
    R.options:
      width: 120

format:
  html:
    theme: cosmo
    toc: true
    code-link: true
    code-copy: true
    code-tools: true
    code-fold: true
    code-overflow: wrap
    grid:
      sidebar-width: 300px
      body-width: 700px
      margin-width: 300px

website:
  title: "Free time & chunking modeling"
  description: "A project about..."
  back-to-top-navigation: true
  page-navigation: true
  search: true
  repo-subdir: quarto
  sidebar: 
   collapse-level: 1
   style: "docked"
   contents: 
     - index.qmd
     - section: "Development notes"
       contents: 
       - "quarto/notes.qmd"
       - auto: "quarto/dev-notebooks/*"
     - section: "Notebooks"
       contents: 
         - section: "Data"
           contents:
             - "quarto/notebooks/data_structure.qmd"
             - "quarto/notebooks/EDA.qmd"
             - "quarto/notebooks/subject_data.qmd"
         - section: "Model 1: Original model"
           contents:
            - "quarto/notebooks/modelling_edas_approach.qmd"
            - "quarto/notebooks/par_identifiability.qmd"
            - "quarto/notebooks/sensitivity-to-tau.qmd"
            - "./quarto/notebooks/exp3_model1.qmd"
         - section: "Model 2: Include encoding time"
           contents:
            - "quarto/notebooks/model_v2.qmd"
     - section: "Function reference"
       contents: quarto/reference/*

editor:
  render-on-save: true
